### PUT request to update a patient
PUT http://localhost:4000/patients/223e4567-e89b-12d3-a456-426614174014
Content-Type: application/json

{
  "name": "Sadid Shaikh",
  "email": "isabella.walker@example.com",
  "address": "420 Willow St, Springfield",
  "dateOfBirth": "1987-10-17"
}

###